[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx esbuild server/index.production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/index.production.js"]

[phases.deploy]
cmds = ["npm prune --production"]

[start]
cmd = "npm start"